In [20]:
from pandas import DataFrame
from sklearn.datasets import fetch_openml
import pandas as pd
import numpy as np

In [26]:
df=pd.read_csv('../data/feature-engineered.csv')
y=pd.read_csv('../data/target.csv')

In [27]:
df.shape

(48790, 107)

In [28]:
for col in df.columns:
    if str(col).upper().__contains__('INCO'):
        print(col)

In [29]:
X = df
X

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week,net-capital,workclass_Local-gov,workclass_Never-worked,workclass_Private,...,native-country_United-States,native-country_Unknown,native-country_Vietnam,native-country_Yugoslavia,age_bin_adult,age_bin_mid,age_bin_senior,hours_bin_normal,hours_bin_high,hours_bin_very_high
0,-0.60,0.405356,-1.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.05,-0.735723,-0.333333,0.000000,0.0,1.896714,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,-0.45,1.322873,0.666667,0.000000,0.0,0.000000,0.000000,1.0,0.0,-1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.35,-0.148399,0.000000,8.947546,0.0,0.000000,8.947546,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,-0.95,-0.621747,0.000000,0.000000,0.0,-2.429708,0.000000,0.0,0.0,-1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48785,-0.50,0.659414,0.666667,0.000000,0.0,-0.434611,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
48786,0.15,-0.197953,-0.333333,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
48787,1.05,-0.218478,-0.333333,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
48788,-0.75,0.194513,-0.333333,0.000000,0.0,-5.814318,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48789,0.75,0.914514,-0.333333,9.617471,0.0,0.000000,9.617471,0.0,0.0,-1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [30]:
from sklearn.feature_selection import VarianceThreshold

selector = VarianceThreshold(threshold=0.01)
X_new = selector.fit_transform(X)

In [31]:
selected_cols = X.columns[selector.get_support()]

X_new = pd.DataFrame(X_new, columns=selected_cols)

In [32]:
print("Original shape:", X.shape)
print("New shape:", X_new.shape)

Original shape: (48790, 107)
New shape: (48790, 58)

In [33]:
X_new

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week,net-capital,workclass_Local-gov,workclass_Private,workclass_Self-emp-inc,...,race_Asian-Pac-Islander,race_Black,race_White,sex_Male,native-country_Mexico,native-country_United-States,native-country_Unknown,age_bin_adult,age_bin_mid,age_bin_senior
0,-0.60,0.405356,-1.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,1.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.05,-0.735723,-0.333333,0.000000,0.0,1.896714,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,-0.45,1.322873,0.666667,0.000000,0.0,0.000000,0.000000,1.0,-1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.35,-0.148399,0.000000,8.947546,0.0,0.000000,8.947546,0.0,0.0,0.0,...,0.0,1.0,-1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,-0.95,-0.621747,0.000000,0.000000,0.0,-2.429708,0.000000,0.0,-1.0,0.0,...,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48785,-0.50,0.659414,0.666667,0.000000,0.0,-0.434611,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0,0.0
48786,0.15,-0.197953,-0.333333,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
48787,1.05,-0.218478,-0.333333,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,1.0,0.0
48788,-0.75,0.194513,-0.333333,0.000000,0.0,-5.814318,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48789,0.75,0.914514,-0.333333,9.617471,0.0,0.000000,9.617471,0.0,-1.0,1.0,...,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [34]:
X_new.to_csv('data/selected-features.csv', index=False)